name: Running Automation Tests

on:
  push:
    branches:
      - actionsTest
  workflow_dispatch:
    inputs:
      BROWSER:
        description: 'Browser used for testing'     
        required: true
        default: 'chrome'
      REMOTELOCAL:
        description: 'soucelabs connection'     
        required: true
        default: 'remote'
      CUCUMBER_OPTIONS:
        description: 'story tags'     
        required: true
        default: 'latest'

env:
  SAUCE_USERNAME: WasylSH # set this to your application's name
  SAUCE_ACCESS_KEY: 050b93a3-bcd6-45b3-b36c-05b8289b4184  # add a secret to your repository, secret's name: SAUCE_ACCESS_KEY

jobs:
  test_job:
    if: github.event_name == 'push'  # this means when feature branch is pushed to dev
    runs-on: ubuntu-latest
    name: Run GUI Test Cases
    steps:
      - name : Create workspace
        uses: actions/checkout@v2
            
      - name : Connect to saucelabs
        uses: saucelabs/sauce-connect-action@v1
        with:
          username: ${{ env.SAUCE_USERNAME }}
          accessKey: ${{ env.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-action-tunnel
          scVersion: 4.6.4
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Run Tests
        run: mvn clean test -DBrowser=${{ github.event.inputs.BROWSER }} -DRemoteLocal=${{ github.event.inputs.REMOTELOCAL }}